"""all3table

Revision ID: 458215b2b7d2
Revises: aeddb5c6e94e
Create Date: 2023-05-18 14:19:44.902501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458215b2b7d2'
down_revision = 'aeddb5c6e94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('from_trainer', sa.Boolean(), nullable=True))
        batch_op.drop_constraint("oldfkey", type_='foreignkey')
        batch_op.create_foreign_key("newfkey-user", 'user', ['user_id'], ['username'])
        batch_op.create_foreign_key("newfkey-trainer", 'trainer', ['trainer_id'], ['username'])
        batch_op.drop_column('userid')

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_column('is_pro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pro', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_constraint("newfkey-trainer", type_='foreignkey')
        batch_op.drop_constraint("newfkey-user", type_='foreignkey')
        batch_op.create_foreign_key("oldfkey", 'user', ['userid'], ['username'])
        batch_op.drop_column('from_trainer')
        batch_op.drop_column('user_id')
        batch_op.drop_column('trainer_id')

    # ### end Alembic commands ###
