"""all3table

Revision ID: aeddb5c6e94e
Revises: 3e019c92dd53
Create Date: 2023-05-18 14:02:11.327532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeddb5c6e94e'
down_revision = '3e019c92dd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainer_name'), ['name'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('from_trainer', sa.Boolean(), nullable=True))
        batch_op.drop_constraint("oldfkey", type_='foreignkey')
        batch_op.create_foreign_key("newfkey-user", 'user', ['user_id'], ['username'])
        batch_op.create_foreign_key("newfkey-trainer", 'trainer', ['trainer_id'], ['username'])
        batch_op.drop_column('userid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_pro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pro', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_constraint("newfkey-user", type_='foreignkey')
        batch_op.drop_constraint("newfkey-trainer", type_='foreignkey')
        batch_op.create_foreign_key("oldfkey", 'user', ['userid'], ['username'])
        batch_op.drop_column('from_trainer')
        batch_op.drop_column('user_id')
        batch_op.drop_column('trainer_id')

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainer_name'))

    op.drop_table('trainer')
    # ### end Alembic commands ###
