"""user

Revision ID: bec3ddfd54a0
Revises: 
Create Date: 2023-05-20 13:03:18.132877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec3ddfd54a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainer_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.Column('fitness_goal', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('current_excercise', sa.Integer(), nullable=True),
    sa.Column('willing_excercise', sa.Integer(), nullable=True),
    sa.Column('allergies', sa.String(length=128), nullable=True),
    sa.Column('other_comments', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=288), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('trainer_id', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.String(length=30), nullable=True),
    sa.Column('from_trainer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.username'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_time'), ['time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_time'))

    op.drop_table('message')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))

    op.drop_table('user')
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainer_name'))

    op.drop_table('trainer')
    # ### end Alembic commands ###
